require 'rubygems'
require 'nokogiri'
require 'open-uri'
require 'cgi'

require File.dirname(__FILE__) + '/legebiltzarra/initiative' 
require File.dirname(__FILE__) + '/legebiltzarra/intervention' 
require File.dirname(__FILE__) + '/legebiltzarra/legislature' 
require File.dirname(__FILE__) + '/legebiltzarra/parliamentarian' 
require File.dirname(__FILE__) + '/legebiltzarra/search' 